# services:
#   app:
#     build: .
#     container_name: inventory_app
#     volumes:
#       - .:/var/www
#     networks:
#       - laravel

#   nginx:
#     image: nginx:alpine
#     container_name: inventory_nginx
#     ports:
#       - "8000:80"
#     volumes:
#       - .:/var/www
#       - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
#     depends_on:
#       - app
#     networks:
#       - laravel

#   mysql:
#     image: mysql:8.0
#     container_name: inventory_mysql
#     environment:
#       MYSQL_DATABASE: inventory_app
#       MYSQL_USER: laravel
#       MYSQL_PASSWORD: laravel
#       MYSQL_ROOT_PASSWORD: root
#     volumes:
#       - mysql_data:/var/lib/mysql
#     networks:
#       - laravel

# networks:
#   laravel:

# volumes:
#   mysql_data:


services:
  app:
    build: .
    container_name: inventory_app
    volumes:
      - .:/var/www
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: inventory_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: inventory_mysql
    environment:
      MYSQL_DATABASE: inventory_app
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  mysql_data:
